apiVersion: v1
kind: Secret
metadata:
  name: cart-secrets
  labels:
    app: cart-service
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Host=postgres-service;Database=cart_db;Username=postgres;Password=<PLACEHOLDER>"
  Jwt__PublicKey: "<PLACEHOLDER>"
  RabbitMQ__Username: "<PLACEHOLDER>"
  RabbitMQ__Password: "<PLACEHOLDER>"
  PaymentService__ApiKey: "<PLACEHOLDER>"
  PaymentService__MerchantId: "<PLACEHOLDER>"
  FiscalService__CertificatePassword: "<PLACEHOLDER>"
  FiscalService__BusinessOib: "<PLACEHOLDER>"
