// <auto-generated />
using System;
using CartService.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CartService.DAL.Data.Migrations
{
    [DbContext(typeof(CartDbContext))]
    [Migration("20260714093650_AddGuestSessionToken")]
    partial class AddGuestSessionToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CartService.DAL.Models.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("GuestSessionToken")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GuestSessionToken")
                        .IsUnique()
                        .HasDatabaseName("IX_Carts_GuestSessionToken")
                        .HasFilter("\"GuestSessionToken\" IS NOT NULL");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_Carts_GuestSessionToken_UpdatedAt")
                        .HasFilter("\"GuestSessionToken\" IS NOT NULL");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("\"GuestSessionToken\" IS NULL");

                    b.ToTable("carts", (string)null);
                });

            modelBuilder.Entity("CartService.DAL.Models.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("UnitPriceAmount")
                        .HasColumnType("integer");

                    b.Property<string>("UnitPriceCurrency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("EUR");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("CartId", "ProductId")
                        .IsUnique();

                    b.ToTable("cart_items", (string)null);
                });

            modelBuilder.Entity("CartService.DAL.Models.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("UnitPriceAmount")
                        .HasColumnType("integer");

                    b.Property<string>("UnitPriceCurrency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("EUR");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("inventory_items", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            AvailableQuantity = 150,
                            ProductId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ProductName = "Wireless Bluetooth Headphones",
                            UnitPriceAmount = 7999,
                            UnitPriceCurrency = "EUR",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            AvailableQuantity = 500,
                            ProductId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ProductName = "USB-C Charging Cable (2m)",
                            UnitPriceAmount = 1299,
                            UnitPriceCurrency = "EUR",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000003"),
                            AvailableQuantity = 75,
                            ProductId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ProductName = "Mechanical Keyboard (TKL)",
                            UnitPriceAmount = 12999,
                            UnitPriceCurrency = "EUR",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000004"),
                            AvailableQuantity = 200,
                            ProductId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ProductName = "Ergonomic Mouse",
                            UnitPriceAmount = 4999,
                            UnitPriceCurrency = "EUR",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000005"),
                            AvailableQuantity = 30,
                            ProductId = new Guid("55555555-5555-5555-5555-555555555555"),
                            ProductName = "27\" 4K Monitor",
                            UnitPriceAmount = 44999,
                            UnitPriceCurrency = "EUR",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000006"),
                            AvailableQuantity = 120,
                            ProductId = new Guid("66666666-6666-6666-6666-666666666666"),
                            ProductName = "Laptop Stand (Aluminum)",
                            UnitPriceAmount = 3499,
                            UnitPriceCurrency = "EUR",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000007"),
                            AvailableQuantity = 90,
                            ProductId = new Guid("77777777-7777-7777-7777-777777777777"),
                            ProductName = "Webcam 1080p",
                            UnitPriceAmount = 5999,
                            UnitPriceCurrency = "EUR",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000008"),
                            AvailableQuantity = 250,
                            ProductId = new Guid("88888888-8888-8888-8888-888888888888"),
                            ProductName = "Desk Lamp (LED, Dimmable)",
                            UnitPriceAmount = 2499,
                            UnitPriceCurrency = "EUR",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000009"),
                            AvailableQuantity = 5,
                            ProductId = new Guid("99999999-9999-9999-9999-999999999999"),
                            ProductName = "Noise Cancelling Earbuds",
                            UnitPriceAmount = 19999,
                            UnitPriceCurrency = "EUR",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000010"),
                            AvailableQuantity = 60,
                            ProductId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            ProductName = "Portable SSD (1TB)",
                            UnitPriceAmount = 8999,
                            UnitPriceCurrency = "EUR",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Shared.Models.Entities.FailedEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("IX_failed_events_unprocessed")
                        .HasFilter("\"ProcessedAt\" IS NULL");

                    b.ToTable("failed_events", (string)null);
                });

            modelBuilder.Entity("CartService.DAL.Models.CartItem", b =>
                {
                    b.HasOne("CartService.DAL.Models.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("CartService.DAL.Models.Cart", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
