apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  labels:
    app: auth-service
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Host=postgres-service;Database=auth_db;Username=postgres;Password=<PLACEHOLDER>"
  Jwt__PrivateKey: "<PLACEHOLDER>"
  Jwt__PublicKey: "<PLACEHOLDER>"
  RabbitMQ__Username: "<PLACEHOLDER>"
  RabbitMQ__Password: "<PLACEHOLDER>"
